[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[[language]]
name = "python"
language-servers = ["pyrefly"]
formatter = { command = 'black', args = ['-', '--fast', '--quiet'] }

[[language]]
name = "cpp"
formatter = { command = 'clang-format', args = ['--style', 'LLVM'] }

[[language]]
name = "c"
formatter = { command = 'clang-format', args = ['--style', 'LLVM'] }

[[language]]
name = "gas"
file-types = ["s", "S"]
formatter = { command = 'asmfmt' }

[[language]]
name = "haskell"
formatter = { command = 'ormolu', args = [ "--no-cabal" ] }

[[language]]
name = "java"
formatter = { command = 'google-java-format', args = [ '-'] }

[[language]]
name = "prolog"
file-types = ["pl"]
