[[language]]
name = "cpp"
formatter = { command = 'clang-format', args = ['--style', 'Chromium'] }

[[language]]
name = "c"
formatter = { command = 'clang-format', args = ['--style', 'Chromium'] }

[[language]]
name = "gas"
file-types = ["s", "S"]
formatter = { command = 'asmfmt' }

